#index:
#    path: /
#    controller: App\Controller\DefaultController::index

all_customers:
      path: /customers
      controller: App\Controller\CustomerController::index

new_customer:
      path: /customers/new
      controller: App\Controller\CustomerController::new

create_customer:
      path: /customers/create
      controller: App\Controller\CustomerController::create
